In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/end-476e-part-4/sample_submission.csv
/kaggle/input/end-476e-part-4/train.csv
/kaggle/input/end-476e-part-4/test.csv

In [29]:
test=pd.read_csv("/kaggle/input/end-476e-part-4/test.csv")
train=pd.read_csv("/kaggle/input/end-476e-part-4/train.csv",index_col=0)

In [5]:
test.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f390,f391,f392,f393,f394,f395,f396,f397,f398,f399
Id,,,,,,,,,,,,,,,,,,,,,
81906,336.022737,-7068.095117,Category_6,105.705528,-6.042960,-7.169588,-970.774117,8,433.428978,8,...,866.236037,-9.443609,551.945878,5,825.798202,6238.930132,-177.829352,-129.555734,-158.565078,NaN
81907,-178.809249,10943.847140,Category_2,-1515.123910,-104.355068,-6.280441,1877.141997,11,-1946.083720,5,...,-405.358606,0.059411,-612.167254,8,396.451079,5310.392054,-379.467134,128.735337,1725.651184,-354.303204
81908,55.804994,-1499.703948,Category_3,-1327.920934,-69.095628,-135.429303,248.580091,3,266.456080,8,...,475.858705,-11.646040,-679.968860,8,NaN,-356.138902,-907.389245,-1328.845823,957.981595,313.553975
81909,-79.462826,-1099.109388,Category_1,663.121523,-125.864987,18.461147,-380.843078,0,1259.076200,6,...,49.154515,-7.640475,206.021785,13,787.863437,320.775295,1120.641273,-536.897673,276.860614,-259.735230
81910,27.735312,-8956.388593,Category_4,124.938943,-18.174790,-63.002303,678.563807,2,2026.758734,1,...,74.118595,-9.612535,-259.285493,9,945.655447,NaN,794.678564,1252.247054,-45.338313,149.985080

# Feature Selection

In [10]:
df=pd.read_csv("/kaggle/input/end-476e-part-4/train.csv",index_col=0)
df.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f391,f392,f393,f394,f395,f396,f397,f398,f399,target
Id,,,,,,,,,,,,,,,,,,,,,
0,-21.383454,4862.264030,Category_1,-121.689849,215.404661,-86.509763,-258.846616,2,-437.328942,8,...,4.718047,NaN,12,640.317405,9395.374661,-2105.081160,-602.595775,1621.953494,-900.375817,0
1,-186.024665,-2051.603665,Category_4,-173.290277,115.727869,-14.392936,-1802.179892,8,265.685599,6,...,7.931293,-306.263061,13,NaN,5909.074474,-182.208954,625.566757,-882.034853,-81.461973,0
2,188.795621,2090.510767,Category_1,-1607.854493,18.333299,-151.079698,-969.652017,4,-921.331365,0,...,12.354731,1028.035345,1,NaN,-523.907883,373.281098,-1271.777225,103.754057,63.622813,1
3,-178.387003,1894.403580,Category_1,-1610.753835,115.857552,NaN,-688.113330,11,1217.982362,8,...,9.708828,406.979253,8,1291.469264,3016.373468,-321.207624,324.417363,269.516800,NaN,0
4,161.846233,7678.458978,Category_1,741.315676,-104.843088,-0.644907,-403.829906,0,-2914.782078,1,...,-6.536001,-145.158907,3,241.347619,-4272.988643,-211.603634,-1218.546050,-721.031369,-967.137994,1

In [11]:
from sklearn.feature_selection import mutual_info_classif

X=df.drop("target",axis=1)
y=df["target"]
X.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f390,f391,f392,f393,f394,f395,f396,f397,f398,f399
Id,,,,,,,,,,,,,,,,,,,,,
0,-21.383454,4862.264030,Category_1,-121.689849,215.404661,-86.509763,-258.846616,2,-437.328942,8,...,-766.179194,4.718047,NaN,12,640.317405,9395.374661,-2105.081160,-602.595775,1621.953494,-900.375817
1,-186.024665,-2051.603665,Category_4,-173.290277,115.727869,-14.392936,-1802.179892,8,265.685599,6,...,708.564572,7.931293,-306.263061,13,NaN,5909.074474,-182.208954,625.566757,-882.034853,-81.461973
2,188.795621,2090.510767,Category_1,-1607.854493,18.333299,-151.079698,-969.652017,4,-921.331365,0,...,486.050447,12.354731,1028.035345,1,NaN,-523.907883,373.281098,-1271.777225,103.754057,63.622813
3,-178.387003,1894.403580,Category_1,-1610.753835,115.857552,NaN,-688.113330,11,1217.982362,8,...,-599.110087,9.708828,406.979253,8,1291.469264,3016.373468,-321.207624,324.417363,269.516800,NaN
4,161.846233,7678.458978,Category_1,741.315676,-104.843088,-0.644907,-403.829906,0,-2914.782078,1,...,NaN,-6.536001,-145.158907,3,241.347619,-4272.988643,-211.603634,-1218.546050,-721.031369,-967.137994

In [12]:
num_cols = [col for col in X.columns if X[col].dtype != "O"]
cat_cols = [col for col in X.columns if X[col].dtype == "O"]

In [14]:
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.feature_selection import SelectKBest, r_regression
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics   
from sklearn.feature_selection import mutual_info_classif


cat_imputer = SimpleImputer(strategy = "most_frequent")
cat_imputer.fit(X_train[cat_cols])
X_train[cat_cols] = cat_imputer.transform(X_train[cat_cols])
X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

In [6]:
X_train=train.drop("target",axis=1)
X_test=test
y_train=train["target"]

In [15]:
num_imputer = SimpleImputer(strategy="mean")
num_imputer.fit(X_train[num_cols])
X_train[num_cols] = num_imputer.transform(X_train[num_cols])
X_test[num_cols] = num_imputer.transform(X_test[num_cols])

In [16]:
X_train.isnull().sum()

f0      0
f1      0
f2      0
f3      0
f4      0
       ..
f395    0
f396    0
f397    0
f398    0
f399    0
Length: 400, dtype: int64

In [ ]:
X.isnull().sum()

In [17]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore").set_output(transform = "pandas")
encoder.fit(X_train[cat_cols])
X_train = pd.concat([X_train.drop(cat_cols, axis = 1),encoder.transform(X_train[cat_cols])], axis = 1)
X_test = pd.concat([X_test.drop(cat_cols, axis = 1),encoder.transform(X_test[cat_cols])] , axis = 1)

In [18]:
selector = SelectKBest(mutual_info_classif,k=100)
selector.fit(X_train, y_train)

X_train = selector.transform(X_train)
X_test = selector.transform(X_test)

In [19]:
X_train

array([[ 8.00000000e+00, -2.01417014e+02,  3.98140510e+03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.00000000e+00,  1.47391593e+03,  2.86720544e+03, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00, -7.54711552e+02,  1.63082020e+03, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.00000000e+00,  2.54732543e+03, -1.17068854e+03, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.00000000e+00, -7.70797796e+02, -4.33055145e+03, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 6.00000000e+00, -2.41715081e+02,  8.13574722e+03, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [21]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier


mdl=RandomForestClassifier()
mdl.fit(X_train,y_train)
ypred= mdl.predict(X_test)

In [30]:
predicted_results = np.column_stack((test.loc[:,["Id"]].astype(int), ypred))
predicted_results

array([[81906,     0],
       [81907,     0],
       [81908,     0],
       ...,
       [99997,     0],
       [99998,     0],
       [99999,     0]])

In [31]:
submission = pd.DataFrame(predicted_results, columns = ['Id', 'target']).set_index('Id')
submission.to_csv('submission_part4.csv')